### PR TITLE
Improves Project error tracking and representation

### PR DESCRIPTION
**Pull request by vulder**
Adds timeout for vara analyses. Implements compile time error tracking 
This includes a rework of error tracking and error file handling, to
separate and reuse errors and file states. Furthermore, status now shows
 each file state separated.

resolves se-passau/VaRA#431
resolves se-passau/VaRA#432
resolves se-passau/VaRA#434

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/paper_config_manager.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3748022&bid=13165568)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/paper_config_manager.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3748022&bid=13165568)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/paper_config_manager.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3748022&bid=13165568)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/paper/paper_config_manager.py  1
         

Clones added
============
- varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3748022&bid=13165568)

**Review by julianbreiteneicher — APPROVED** [review]
Looks good! :+1:

**Pull request merged**
