### PR TITLE
Adds linkage checker project

### PR DESCRIPTION
**Pull request by vulder**
The linker checker project can be build to test if the used compilers
are can correctly load their shared libraries.

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/test_projects/linker_check.py  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5521173&bid=18088529)

**Review by boehmseb — CHANGES_REQUESTED** [review]
I guess you need to merge #283 first  :wink:

**Comment by vulder** [comment]
jop jop

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/test_projects/linker_check.py  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5521173&bid=18088529)

**Review by boehmseb — APPROVED** [review]

**Pull request merged**
