### PR TITLE
Initial case study tool with status

### PR DESCRIPTION
**Pull request by vulder**
Initial case-study tool implementation to allow easier handling of case studies.
Currently we support: status (to print the current state)

resolves se-passau/VaRA#402
related se-passau/VaRA#410

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ varats/experiments/GitBlameAnnotationReport.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3590656&bid=12742780)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ varats/experiments/GitBlameAnnotationReport.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3590656&bid=12742780)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ varats/experiments/GitBlameAnnotationReport.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3590656&bid=12742780)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ varats/experiments/GitBlameAnnotationReport.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3590656&bid=12742780)

**Review by julianbreiteneicher — APPROVED** [review]
works and looks good :+1:

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ varats/experiments/GitBlameAnnotationReport.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3590656&bid=12742780)

**Pull request merged**
