### PR TITLE
Adds list command list available paper config

### PR DESCRIPTION
**Pull request by vulder**

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_paper_config.py  1
         

Clones removed
==============
+ varats/tools/driver_paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5441472&bid=17844226)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_paper_config.py  1
         

Clones removed
==============
+ varats/tools/driver_paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5441472&bid=17844226)

**Review by boehmseb — APPROVED** [review]
lgtm

**Review by boehmseb — CHANGES_REQUESTED** [review]
A short entry in the docs would be nice

**Review by boehmseb — APPROVED** [review]
lgtm

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_paper_config.py  1
         

Clones removed
==============
+ varats/tools/driver_paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5441472&bid=17844226)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/tools/driver_paper_config.py  1
         

Clones removed
==============
+ varats/tools/driver_paper_config.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5441472&bid=17844226)

**Pull request merged**
