### PR TITLE
Adds 4 new projects to the tool suite

### PR DESCRIPTION
**Pull request by vulder**
New projects:
  redis
  htop
  lz4
  curl

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/curl.py  3
- varats/projects/c_projects/lz4.py  3
- varats/projects/c_projects/redis.py  3
- varats/projects/c_projects/htop.py  3
         

Clones added
============
- varats/projects/c_projects/libvpx.py  2
- varats/projects/c_projects/curl.py  12
- varats/projects/c_projects/tmux.py  3
- varats/projects/c_projects/coreutils.py  2
- varats/projects/c_projects/qemu.py  1
- varats/projects/c_projects/busybox.py  3
- varats/projects/c_projects/lz4.py  13
- varats/projects/c_projects/redis.py  9
- varats/projects/c_projects/gravity.py  1
- varats/projects/c_projects/htop.py  14
- varats/projects/c_projects/lrzip.py  2
- varats/projects/c_projects/glibc.py  2
- varats/projects/c_projects/openssl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5520555&bid=18086779)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/curl.py  3
- varats/projects/c_projects/lz4.py  3
- varats/projects/c_projects/htop.py  3
- varats/projects/c_projects/redis.py  3
         

Clones added
============
- varats/projects/c_projects/busybox.py  3
- varats/projects/c_projects/tmux.py  3
- varats/projects/c_projects/gravity.py  1
- varats/projects/c_projects/openssl.py  2
- varats/projects/c_projects/coreutils.py  2
- varats/projects/c_projects/qemu.py  1
- varats/projects/c_projects/glibc.py  2
- varats/projects/c_projects/curl.py  12
- varats/projects/c_projects/lz4.py  13
- varats/projects/c_projects/htop.py  14
- varats/projects/c_projects/redis.py  9
- varats/projects/c_projects/libvpx.py  2
- varats/projects/c_projects/lrzip.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5520555&bid=18086779)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/redis.py  3
- varats/projects/c_projects/curl.py  3
- varats/projects/c_projects/htop.py  3
- varats/projects/c_projects/lz4.py  3
         

Clones added
============
- varats/projects/c_projects/redis.py  9
- varats/projects/c_projects/gravity.py  1
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/curl.py  11
- varats/projects/c_projects/busybox.py  2
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/lrzip.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/htop.py  13
- varats/projects/c_projects/lz4.py  12
- varats/projects/c_projects/coreutils.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5520555&bid=18086779)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/projects/c_projects/curl.py  3
- varats/projects/c_projects/htop.py  3
- varats/projects/c_projects/lz4.py  3
- varats/projects/c_projects/redis.py  3
         

Clones added
============
- varats/projects/c_projects/lrzip.py  1
- varats/projects/c_projects/coreutils.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/gravity.py  1
- varats/projects/c_projects/busybox.py  2
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/curl.py  11
- varats/projects/c_projects/htop.py  13
- varats/projects/c_projects/tmux.py  2
- varats/projects/c_projects/lz4.py  12
- varats/projects/c_projects/redis.py  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5520555&bid=18086779)

**Review by boehmseb — APPROVED** [review]
lgtm

**Pull request merged**
