### PR TITLE
Adds new BinaryType to BinaryWrappers

### PR DESCRIPTION
**Pull request by vulder**
resolves se-passau/VaRA#670

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/busybox.py  1
- varats/varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/busybox.py  1
- varats/varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/busybox.py  1
- varats/varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/busybox.py  1
- varats/varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/glibc.py  1
- varats/varats/projects/c_projects/busybox.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/busybox.py  1
- varats/varats/projects/c_projects/glibc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/glibc.py  1
- varats/varats/projects/c_projects/busybox.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/glibc.py  1
- varats/varats/projects/c_projects/busybox.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/glibc.py  1
- varats/varats/projects/c_projects/busybox.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/glibc.py  1
- varats/varats/projects/c_projects/busybox.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/glibc.py  1
- varats/varats/projects/c_projects/busybox.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/varats/projects/c_projects/glibc.py  1
- varats/varats/projects/c_projects/busybox.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6133091&bid=20057164)

**Review by boehmseb — APPROVED** [review]

**Pull request merged**
