### PR TITLE
Added auto handling for VaRA repositories

### PR DESCRIPTION
**Pull request by vulder**
Small tool to ease development by providing git multiplexing on all projects.

resolves se-passau/VaRA#351

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/driver.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3538162&bid=12588187)

**Comment by julianbreiteneicher** [comment]
I created a completely fresh VaRA-TS instance (new vara config, new git clone) and apparently
the `llvm_source_dir` config parameter is not set. So `vd` fails for me b.c. the value is null.
EDIT: I guess this parameter should be set automatically by the toolsuite?

**Comment by julianbreiteneicher** [comment]
Can I use the `checkout` subcommand to checkout the default branches?
These aren't the same for all projects (`vara-dev` for VaRA, `vara-80-dev` for llvm/clang and `release_80` for the others), but I think being able to do that with one command would be useful.

Example use case: I am currently working on feature f-Foo, but now I want to begin with a second feature f-Bar. If I simply use `vd new-branch f-Bar llvm` ,for example, then the f-Bar branch will be based on f-Foo and not on vara-80-dev, as it should be.

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/driver.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3538162&bid=12588187)

**Review by julianbreiteneicher — CHANGES_REQUESTED** [review]
Now, the application crashes as soon as I open the build setup window:

```
Traceback (most recent call last):
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/gui/main_window.py", line 57, in _spawn_vara_build_setup
    self.bwg = BuildSetup()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/gui/buildsetup_window.py", line 115, in __init__
    self._update_source_dir()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/gui/buildsetup_window.py", line 272, in _update_source_dir
    self._check_state()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/gui/buildsetup_window.py", line 218, in _check_state
    self._check_init()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/gui/buildsetup_window.py", line 223, in _check_init
    self.vara_state_mgr.change_llvm_source_folder(path)
AttributeError: 'BuildSetup' object has no attribute 'vara_state_mgr'
[1]    1092 abort (core dumped)  vara-graphview
```

Steps to reproduce:
  - Launch `vara-graphview` in a clean directory without a `.vara.yaml` config
  - Accept the creation of the config
  - Launch build setup window

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/driver.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3538162&bid=12588187)

**Review by julianbreiteneicher — COMMENTED** [review]
works now :+1:

**Review by julianbreiteneicher — APPROVED** [review]

**Pull request merged**
