### PR TITLE
Adds support to restrict plots to a case study

### PR DESCRIPTION
**Pull request by vulder**
resolves se-passau/VaRA#403

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/plots.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3714635&bid=13080150)

**Review by julianbreiteneicher — CHANGES_REQUESTED** [review]
I am unable to successfully execute the program:

```
(vara-tool-suite) [jb@scotty ~/work/hiwi:master*] vara-gen-graph -r results/gzip/ -p gzip -c paper_configs/small_gzip/cm.txt.cmap interaction_plot
Traceback (most recent call last):
  File "/home/jb/opt/virtualenvs/vara-tool-suite/bin/vara-gen-graph", line 11, in <module>
    load_entry_point('VaRA-Tool-Suite', 'console_scripts', 'vara-gen-graph')()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/driver.py", line 263, in main_gen_graph
    build_plot(**args)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/plot_utils.py", line 28, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/plots.py", line 48, in build_plot
    plot.save('png')
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/commit_interactions.py", line 215, in save
    self.plot()
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/commit_interactions.py", line 208, in plot
    cs_filter(_gen_interaction_graph(**self.__saved_extra_args)))
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/plot_utils.py", line 28, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/commit_interactions.py", line 126, in _gen_interaction_graph
    str(project_name))
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/commit_interactions.py", line 46, in _build_interaction_table
    report_file for report_file in report_files
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/commit_interactions.py", line 47, in <listcomp>
    if not report_in_data_frame(report_file, cached_df['head_cm'])
  File "/home/jb/work/hiwi/repos/VaRA-Tool-Suite/varats/plots/commit_interactions.py", line 43, in report_in_data_frame
    return (match.group("file_commit_hash") == df_col).any()
AttributeError: 'NoneType' object has no attribute 'group'
```
Am I doing smth. wrong?

**Comment by vulder** [comment]
hmm, this is not related to the change

do you have wrongly named results in your result folder?

The file regex does not match but your file starts with the correct ''start'

**Comment by julianbreiteneicher** [comment]
A right. Yes I do. That's why a recent pull request of mine solved a similar issue by skipping files that don't match the regex

**Comment by vulder** [comment]
tmux-tmux-da359269cb_92c5e562-40fc-46a0-ac0f-4ad9613a3ed1.yaml
project-binary-commithash-UUID.yaml

if the binary is not their, you did not update all your old file names

**Comment by julianbreiteneicher** [comment]
Hmm, now it generates a graph, but it doesn't contain anything:

```
vara-gen-graph -r results/gzip/ -p gzip -c paper_configs/small_gzip/cm.txt.cmap interaction_plot
```
gzip_interaction_graph

**Comment by vulder** [comment]
do you have results?

```console
ls -l results/gzip
```

**Comment by julianbreiteneicher** [comment]
The yaml file is 34MB as usual

**Comment by vulder** [comment]
this plot tracks changes over time, you have to supply more than one file

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/plots/plots.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3714635&bid=13080150)

**Comment by julianbreiteneicher** [comment]
All right, I was holding it wrong. :)
Seems to work now! :)

**Review by julianbreiteneicher — APPROVED** [review]

**Pull request merged**
