### PR TITLE
Refactored vara setup

### PR DESCRIPTION
**Pull request by vulder**
Moved project related paths and constants into own class, allowing easier management and adding of projects.

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/vara_manager.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3436734&bid=12315786)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/vara_manager.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3436734&bid=12315786)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/vara_manager.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3436734&bid=12315786)

**Comment by julianbreiteneicher** [comment]
`mock` is missing as dependency in `requirements.txt`

**Review by julianbreiteneicher — CHANGES_REQUESTED** [review]
- `mock` is missing as dependency in `requirements.txt`
- the default version for VaRA is still 70 instead of 80

otherwise it works fine

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- varats/vara_manager.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/VaRA/VaRA-Tool-Suite/pullRequest?prid=3436734&bid=12315786)

**Pull request merged**
