### PR TITLE
Warn if UnaryFilter is used w/o Source-/TargetOperator

### PR DESCRIPTION
**Pull request by julianbreiteneicher**
Example:
2019-07-02-235643_600x657_scrot

### CODE REVIEW

**Comment by vulder** [comment]
maybe: `Currently this filter applies to source and target, therefore, only interactions where both satisfy the filter are included.`

**Review by vulder — COMMENTED** [review]
maybe: `Currently this filter applies to source and target, therefore, only interactions where both satisfy the filter are included.`

**Review by vulder — APPROVED** [review]

**Comment by julianbreiteneicher** [comment]
> maybe: `Currently this filter applies to source and target, therefore, only interactions where both satisfy the filter are included.`

Sure, I could easily change that...?

**Comment by julianbreiteneicher** [comment]
Done.
2019-07-04-231318_633x694_scrot

**Pull request merged**
