### PR TITLE
Reopen: Disable shallow git clone for currently used case study projects

### PR DESCRIPTION
**Pull request by vulder**

### CODE REVIEW

**Comment by vulder** [comment]
@julianbreiteneicher is everything on the BB side merged? can we bump the required version and merge?

**Comment by julianbreiteneicher** [comment]
@vulder Almost. One PR needs to be merged, then it's ready.

**Comment by vulder** [comment]
ok then we'll wait a bit more :)
can you reference the PR in a comment

**Comment by julianbreiteneicher** [comment]
Sure, it's PR PolyJIT/benchbuild#221

**Comment by julianbreiteneicher** [comment]
We can merge this after se-passau/VaRA-Tool-Suite#121 has been merged.

**Pull request merged**
