### PR TITLE
Add 15 C Projects which use OpenSSL EVP

### PR DESCRIPTION
**Pull request by fabianbs96**

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 52
           

Complexity increasing per file
==============================
- varats/projects/c_projects/liboqs.py  3
- varats/projects/c_projects/magma.py  2
- varats/projects/c_projects/openvpn.py  3
- varats/projects/c_projects/FreeBSD.py  2
- varats/projects/c_projects/nmap.py  2
- varats/projects/c_projects/wazuh.py  2
- varats/projects/c_projects/OpenSC.py  2
- varats/projects/c_projects/u-boot.py  2
- varats/projects/c_projects/moloch.py  2
- varats/projects/c_projects/themis.py  2
- varats/projects/c_projects/SoftEtherVPN.py  2
- varats/projects/c_projects/zcoin.py  2
- varats/projects/c_projects/openssh.py  3
- varats/projects/c_projects/s2n.py  3
- varats/projects/c_projects/n2n.py  2
         

Clones added
============
- varats/projects/c_projects/liboqs.py  2
- varats/projects/c_projects/magma.py  3
- varats/projects/c_projects/openvpn.py  5
- varats/projects/c_projects/FreeBSD.py  3
- varats/projects/c_projects/nmap.py  3
- varats/projects/c_projects/wazuh.py  3
- varats/projects/c_projects/OpenSC.py  3
- varats/projects/c_projects/u-boot.py  3
- varats/projects/c_projects/moloch.py  3
- varats/projects/c_projects/themis.py  2
- varats/projects/c_projects/SoftEtherVPN.py  3
- varats/projects/c_projects/zcoin.py  3
- varats/projects/c_projects/openssh.py  4
- varats/projects/c_projects/s2n.py  2
- varats/projects/c_projects/n2n.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6187613&bid=20191672)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 70
           

Complexity increasing per file
==============================
- varats/varats/projects/c_projects/OpenSC.py  3
- varats/varats/projects/c_projects/themis.py  3
- varats/varats/projects/c_projects/nmap.py  3
- varats/varats/projects/c_projects/n2n.py  3
- varats/varats/projects/c_projects/openssh.py  3
- varats/varats/projects/c_projects/u-boot.py  3
- varats/varats/projects/c_projects/SoftEtherVPN.py  3
- varats/varats/projects/c_projects/zcoin.py  3
- varats/varats/projects/c_projects/magma.py  3
- varats/varats/projects/c_projects/s2n.py  3
- varats/varats/projects/c_projects/moloch.py  3
- varats/varats/projects/c_projects/liboqs.py  3
- varats/varats/projects/c_projects/wazuh.py  3
         

Clones added
============
- varats/varats/projects/c_projects/OpenSC.py  10
- varats/varats/projects/c_projects/themis.py  5
- varats/varats/projects/c_projects/nmap.py  8
- varats/varats/projects/c_projects/n2n.py  7
- varats/varats/projects/c_projects/openssh.py  7
- varats/varats/projects/c_projects/u-boot.py  5
- varats/varats/projects/c_projects/SoftEtherVPN.py  4
- varats/varats/projects/c_projects/zcoin.py  5
- varats/varats/projects/c_projects/magma.py  2
- varats/varats/projects/c_projects/s2n.py  2
- varats/varats/projects/c_projects/moloch.py  2
- varats/varats/projects/c_projects/liboqs.py  3
- varats/varats/projects/c_projects/wazuh.py  5
- varats/varats/projects/c_projects/FreeBSD.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6187613&bid=20191672)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 70
           

Complexity increasing per file
==============================
- varats/varats/projects/c_projects/SoftEtherVPN.py  3
- varats/varats/projects/c_projects/moloch.py  3
- varats/varats/projects/c_projects/s2n.py  3
- varats/varats/projects/c_projects/nmap.py  3
- varats/varats/projects/c_projects/OpenSC.py  3
- varats/varats/projects/c_projects/zcoin.py  3
- varats/varats/projects/c_projects/n2n.py  3
- varats/varats/projects/c_projects/magma.py  3
- varats/varats/projects/c_projects/themis.py  3
- varats/varats/projects/c_projects/u-boot.py  3
- varats/varats/projects/c_projects/liboqs.py  3
- varats/varats/projects/c_projects/openssh.py  3
- varats/varats/projects/c_projects/wazuh.py  3
         

Clones added
============
- varats/varats/projects/c_projects/SoftEtherVPN.py  4
- varats/varats/projects/c_projects/moloch.py  2
- varats/varats/projects/c_projects/s2n.py  2
- varats/varats/projects/c_projects/nmap.py  8
- varats/varats/projects/c_projects/FreeBSD.py  3
- varats/varats/projects/c_projects/OpenSC.py  10
- varats/varats/projects/c_projects/zcoin.py  5
- varats/varats/projects/c_projects/n2n.py  7
- varats/varats/projects/c_projects/magma.py  2
- varats/varats/projects/c_projects/themis.py  5
- varats/varats/projects/c_projects/u-boot.py  5
- varats/varats/projects/c_projects/liboqs.py  3
- varats/varats/projects/c_projects/openssh.py  7
- varats/varats/projects/c_projects/wazuh.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6187613&bid=20191672)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 94
           

Complexity increasing per file
==============================
- varats/varats/projects/c_projects/openssh.py  3
- varats/varats/projects/c_projects/liboqs.py  3
- varats/varats/projects/c_projects/moloch.py  3
- varats/varats/projects/c_projects/magma.py  3
- varats/varats/projects/c_projects/FreeBSD.py  3
- varats/varats/projects/c_projects/u-boot.py  3
- varats/varats/projects/c_projects/n2n.py  3
- varats/varats/projects/c_projects/SoftEtherVPN.py  3
- varats/varats/projects/c_projects/s2n.py  3
- varats/varats/projects/c_projects/wazuh.py  3
- varats/varats/projects/c_projects/zcoin.py  3
- varats/varats/projects/c_projects/OpenSC.py  3
- varats/varats/projects/c_projects/nmap.py  3
- varats/varats/projects/c_projects/themis.py  3
         

Clones added
============
- varats/varats/projects/c_projects/openssh.py  5
- varats/varats/projects/c_projects/liboqs.py  2
- varats/varats/projects/c_projects/moloch.py  2
- varats/varats/projects/c_projects/magma.py  2
- varats/varats/projects/c_projects/FreeBSD.py  2
- varats/varats/projects/c_projects/u-boot.py  4
- varats/varats/projects/c_projects/n2n.py  7
- varats/varats/projects/c_projects/SoftEtherVPN.py  3
- varats/varats/projects/c_projects/s2n.py  3
- varats/varats/projects/c_projects/wazuh.py  4
- varats/varats/projects/c_projects/zcoin.py  4
- varats/varats/projects/c_projects/OpenSC.py  9
- varats/varats/projects/c_projects/nmap.py  7
- varats/varats/projects/c_projects/themis.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=6187613&bid=20191672)

**Comment by vulder** [comment]
I updated a loot in the past and changed how the CI works, it would be good if you merge the current vara-dev into this PR.
Should this break anything, feel free to contact me if you need help.

**Comment by vulder** [comment]
@fabianbs96 Hoi, what's the state here? Do you still need some of these projects?

The PR is quite old and uses lots of old APIs, we should at some point clean this up.

**Comment by fabianbs96** [comment]
Hi @vulder, I don't really need this anymore. We can see whether it is worth cleaning this up, or to close it.

**Comment by vulder** [comment]
Ok, then we'll clean this up by integrating what we need and drop the rest. @boehmseb needs some of the projects anyhow, so a bit will survive.

**Pull request closed without merging**
