### PR TITLE
Migrates vara projects to new BB job accessor function

### PR DESCRIPTION
**Pull request by vulder**
BenchBuild added new functionality to dynamically select the number of
jobs, depending on the current avialable threads. This update allows
VaRA users to specify 0 as the number of jobs to signal BB to detect the
job amount at runtime.

### CODE REVIEW

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/gravity.py  2
- varats/projects/c_projects/busybox.py  1
- varats/projects/c_projects/vim.py  3
- varats/projects/c_projects/lz4.py  1
- varats/projects/c_projects/gzip.py  2
- varats/projects/c_projects/redis.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/x264.py  2
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/coreutils.py  2
- varats/projects/c_projects/qemu.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5543093&bid=18173643)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/projects/c_projects/gravity.py  2
- varats/projects/c_projects/lz4.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/opus.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/redis.py  2
- varats/projects/c_projects/qemu.py  1
- varats/projects/c_projects/vim.py  3
- varats/projects/c_projects/coreutils.py  2
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/busybox.py  1
- varats/projects/c_projects/gzip.py  2
- varats/projects/c_projects/x264.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5543093&bid=18173643)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/qemu.py  1
- varats/projects/c_projects/xz.py  2
- varats/projects/c_projects/vim.py  3
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/coreutils.py  2
- varats/projects/c_projects/x264.py  2
- varats/projects/c_projects/gravity.py  2
- varats/projects/c_projects/libvpx.py  1
- varats/projects/c_projects/gzip.py  2
- varats/projects/c_projects/redis.py  2
- varats/projects/c_projects/busybox.py  1
- varats/projects/c_projects/lz4.py  1
- varats/projects/c_projects/opus.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5543093&bid=18173643)

**Comment by vulder** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- varats/projects/c_projects/busybox.py  1
- varats/projects/c_projects/gzip.py  2
- varats/projects/c_projects/gravity.py  1
- varats/projects/c_projects/redis.py  1
- varats/projects/c_projects/openssl.py  1
- varats/projects/c_projects/lz4.py  1
- varats/projects/c_projects/glibc.py  1
- varats/projects/c_projects/coreutils.py  1
         

Clones removed
==============
+ varats/projects/c_projects/tmux.py  -1
+ varats/projects/c_projects/vim.py  -1
+ varats/projects/c_projects/htop.py  -1
+ varats/projects/c_projects/lrzip.py  -1
+ varats/projects/c_projects/opus.py  -1
+ varats/projects/c_projects/curl.py  -1
+ varats/projects/c_projects/git.py  -1
+ varats/projects/c_projects/xz.py  -1
+ varats/projects/c_projects/libvpx.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/se-passau/VaRA-Tool-Suite/pullRequest?prid=5543093&bid=18173643)

**Review by boehmseb — APPROVED** [review]
lgtm

**Pull request merged**
